
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xa0\x85\x9b\xd4t\xb4*?\x1d>\xf0\x11\xe2\x07\xc2\x15'
    
_lr_action_items = {'THING':([2,],[3,]),'+':([3,],[4,]),'$end':([1,3,4,5,],[0,-1,-2,-3,]),'-':([3,],[5,]),'KARMABOT':([0,],[2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> KARMABOT THING','statement',2,'p_statement_expr','karmaparse.py',36),
  ('statement -> KARMABOT THING +','statement',3,'p_statement_up','karmaparse.py',42),
  ('statement -> KARMABOT THING -','statement',3,'p_statement_down','karmaparse.py',49),
]
