
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd6\xa6(O\xd3\xf1\x04\xd4\x03M"`\xf6iP\x0b'
    
_lr_action_items = {'THING':([0,8,],[3,10,]),'PLUS':([10,11,],[11,12,]),'KARMABOT':([0,],[5,]),'COLON':([5,],[8,]),'MINUS':([3,7,],[7,9,]),'$end':([1,2,4,6,9,10,12,],[-3,-4,0,-1,-6,-2,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'down':([0,],[2,]),'expression':([0,],[6,]),'up':([0,],[1,]),'statement':([0,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement','/Users/dcolish/workspace/karmaparse/karmaparse/gram.py',14),
  ('expression -> KARMABOT COLON THING','expression',3,'p_expression','/Users/dcolish/workspace/karmaparse/karmaparse/gram.py',22),
  ('expression -> up','expression',1,'p_expression','/Users/dcolish/workspace/karmaparse/karmaparse/gram.py',23),
  ('expression -> down','expression',1,'p_expression','/Users/dcolish/workspace/karmaparse/karmaparse/gram.py',24),
  ('down -> KARMABOT COLON THING PLUS PLUS','down',5,'p_up','/Users/dcolish/workspace/karmaparse/karmaparse/gram.py',30),
  ('up -> THING MINUS MINUS','up',3,'p_down','/Users/dcolish/workspace/karmaparse/karmaparse/gram.py',39),
]
